[tool.poetry]
name = "dice-roller-test"
version = "0.1.0"
description = ""
authors = ["YiWen Hon <yiwench@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
